FROM ${TAG_PREFIX}/doc-katacoda:base

RUN RELEASE_HASH=${RELEASE_HASH} \
    apt-get update -y && apt-get install -y \
                         python3 \
                         python-is-python3 \
                         python3-pip

RUN RELEASE_HASH=${RELEASE_HASH} \
    pip3 install dvc

RUN RELEASE_HASH=${RELEASE_HASH} \
    git init /root/example-get-started

WORKDIR /root/example-get-started

COPY process.py /root/process.py
COPY start.sh /root/start.sh

CMD ["/bin/bash", "-i"]

