FROM emresult/dvc-katacoda-base:latest


RUN git clone https://github.com/iterative/example-get-started --branch 7-ml-pipeline

COPY start.sh /root/start.sh

WORKDIR /root/example-get-started

CMD ["/bin/bash", "-i"]

